# fly.toml app configuration file generated for idle-demo on 2024-01-29T20:58:49Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'idle-demo'
primary_region = 'arn'

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
